version: '3'

tasks:
  up:
    desc: Start all services
    cmds:
      - docker compose up -d

  down:
    desc: Stop all services
    cmds:
      - docker compose down

  down-volumes:
    desc: Stop all services and remove volumes
    cmds:
      - docker compose down -v

  build:
    desc: Build all services
    cmds:
      - docker compose build

  rebuild:
    desc: Rebuild and start all services
    cmds:
      - docker compose up -d --build

  logs:
    desc: Show logs from all services
    cmds:
      - docker compose logs -f

  logs-backend:
    desc: Show logs from backend service
    cmds:
      - docker compose logs -f backend

  shell:
    desc: Open shell in backend container
    cmds:
      - docker compose exec backend bash

  db-shell:
    desc: Open PostgreSQL shell
    cmds:
      - docker compose exec postgres psql -U payroll_user -d payroll_db

  migrate:
    desc: Run database migrations
    cmds:
      - docker compose exec backend alembic upgrade head

  migrate-create:
    desc: Create new migration
    cmds:
      - docker compose exec backend alembic revision --autogenerate -m "{{.CLI_ARGS}}"

  migrate-downgrade:
    desc: Downgrade one migration
    cmds:
      - docker compose exec backend alembic downgrade -1

  test-setup:
    desc: Setup test database and check migrations
    cmds:
      - docker compose exec -T postgres psql -U payroll_user -d payroll_db -c "DROP DATABASE IF EXISTS payroll_db_test;"
      - docker compose exec -T postgres psql -U payroll_user -d payroll_db -c "CREATE DATABASE payroll_db_test;"
      - docker compose exec backend alembic current
      - docker compose exec backend alembic check

  test:
    desc: Run all tests
    deps: [test-setup]
    cmds:
      - docker compose exec backend pytest app/ -v

  test-employee:
    desc: Run employee module tests
    cmds:
      - docker compose exec backend pytest app/modules/employee/tests/ -v

  test-contract:
    desc: Run contract module tests
    cmds:
      - docker compose exec backend pytest app/modules/contract/tests/ -v

  test-compensation:
    desc: Run compensation module tests
    cmds:
      - docker compose exec backend pytest app/modules/compensation/tests/ -v

  test-absence:
    desc: Run absence module tests
    cmds:
      - docker compose exec backend pytest app/modules/absence/tests/ -v

  test-timesheet:
    desc: Run timesheet module tests
    cmds:
      - docker compose exec backend pytest app/modules/timesheet/tests/ -v

  test-reporting:
    desc: Run reporting module tests
    cmds:
      - docker compose exec backend pytest app/modules/reporting/tests/ -v

  test-coverage:
    desc: Run tests with coverage report
    deps: [test-setup]
    cmds:
      - docker compose exec backend pytest app/ --cov=app --cov-report=html --cov-report=xml --cov-report=term

  test-watch:
    desc: Run tests in watch mode
    cmds:
      - docker compose exec backend pytest-watch app/ -v

  lint:
    desc: Run linting with ruff
    cmds:
      - docker compose exec backend ruff check app/

  lint-fix:
    desc: Run linting and auto-fix
    cmds:
      - docker compose exec backend ruff check --fix app/

  format:
    desc: Format code
    cmds:
      - docker compose exec backend ruff format app/

  format-check:
    desc: Check formatting
    cmds:
      - docker compose exec backend ruff format --check app/

  type-check:
    desc: Run type checking
    cmds:
      - docker compose exec backend mypy app/

  clean:
    desc: Clean Python cache files
    cmds:
      - "find backend -type d -name '__pycache__' -exec rm -rf {} +"
      - "find backend -type f -name '*.pyc' -delete"
      - "find backend -type d -name '.pytest_cache' -exec rm -rf {} +"

  reset-db:
    desc: Reset database (drop volumes, restart)
    cmds:
      - docker compose down -v
      - docker compose up -d postgres
      - sleep 3
      - docker compose up -d backend

  restart:
    desc: Restart all services
    cmds:
      - docker compose restart

  restart-backend:
    desc: Restart backend
    cmds:
      - docker compose restart backend

  ps:
    desc: Show running containers
    cmds:
      - docker compose ps

  health:
    desc: Check health of all services
    cmds:
      - curl -s http://localhost:8000/health | jq .
      - "echo 'RabbitMQ Management: http://localhost:15672'"
      - "echo 'PostgreSQL: localhost:5432'"
      - "echo 'Redis: localhost:6379'"

  api-docs:
    desc: Open API documentation
    cmds:
      - "echo 'Opening API docs at http://localhost:8000/docs'"
      - "xdg-open http://localhost:8000/docs 2>/dev/null || open http://localhost:8000/docs 2>/dev/null || echo 'Please open http://localhost:8000/docs manually'"

  install-task:
    desc: Install Taskfile globally
    cmds:
      - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin

  # Frontend Tasks
  frontend-install:
    desc: Install frontend dependencies
    dir: frontend
    cmds:
      - npm install

  frontend-dev:
    desc: Start frontend development server
    dir: frontend
    cmds:
      - npm run dev

  frontend-build:
    desc: Build frontend for production
    dir: frontend
    cmds:
      - npm run build

  frontend-test:
    desc: Run frontend tests
    dir: frontend
    cmds:
      - npm test -- --run

  frontend-test-watch:
    desc: Run frontend tests in watch mode
    dir: frontend
    cmds:
      - npm test

  frontend-test-ui:
    desc: Run frontend tests with UI
    dir: frontend
    cmds:
      - npm run test:ui

  frontend-test-coverage:
    desc: Run frontend tests with coverage
    dir: frontend
    cmds:
      - npm run test:coverage

  frontend-lint:
    desc: Run frontend linting
    dir: frontend
    cmds:
      - npm run lint

  frontend-lint-fix:
    desc: Run frontend linting and auto-fix
    dir: frontend
    cmds:
      - npm run lint:fix

  frontend-format:
    desc: Format frontend code
    dir: frontend
    cmds:
      - npm run format

  frontend-format-check:
    desc: Check frontend code formatting
    dir: frontend
    cmds:
      - npx prettier --check "src/**/*.{ts,tsx,js,jsx,json,css,md}"

  frontend-typecheck:
    desc: Run frontend type checking
    dir: frontend
    cmds:
      - npx tsc --noEmit

  frontend-clean:
    desc: Clean frontend build artifacts
    dir: frontend
    cmds:
      - rm -rf dist node_modules/.vite

  ci-backend:
    desc: Run CI
    cmds:
      - task: format-check
      - task: lint
      - task: type-check
      - task: test-coverage

  ci-frontend:
    desc: Run frontend CI pipeline locally (mirrors GitHub Actions)
    dir: frontend
    cmds:
      - npm ci
      - npx prettier --check "src/**/*.{ts,tsx,js,jsx,json,css,md}"
      - npm run lint
      - npx tsc --noEmit
      - npm run test:coverage
      - npm run build

  ci:
    desc: Run full CI pipeline (backend + frontend) locally
    cmds:
      - task: ci-backend
      - task: ci-frontend

  # Combined Tasks
  test-all:
    desc: Run all tests (backend + frontend)
    cmds:
      - task: test-coverage
      - task: frontend-test-coverage

  lint-all:
    desc: Run all linting (backend + frontend)
    cmds:
      - task: lint
      - task: frontend-lint

  format-all:
    desc: Format all code (backend + frontend)
    cmds:
      - task: format
      - task: frontend-format

  check-all:
    desc: Run all checks (lint, format, type-check, tests)
    cmds:
      - task: format-check
      - task: lint
      - task: type-check
      - task: frontend-format-check
      - task: frontend-lint
      - task: frontend-typecheck
      - task: test-all

  help:
    desc: Show help
    cmds:
      - task --list
