"""add_absence_tables

Revision ID: 126b2645ac16
Revises: 3c511d625d67
Create Date: 2025-11-28 09:24:24.095500

"""
from alembic import op
import sqlalchemy as sa


revision = '126b2645ac16'
down_revision = '3c511d625d67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('absence_balances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('absence_type', sa.Enum('VACATION', 'SICK_LEAVE', 'PARENTAL_LEAVE', 'UNPAID_LEAVE', 'BEREAVEMENT', 'STUDY_LEAVE', 'COMPASSIONATE', name='absencetype'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_days', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('used_days', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_absence_balances_employee_id'), 'absence_balances', ['employee_id'], unique=False)
    op.create_index(op.f('ix_absence_balances_year'), 'absence_balances', ['year'], unique=False)
    op.create_table('absences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('absence_type', sa.Enum('VACATION', 'SICK_LEAVE', 'PARENTAL_LEAVE', 'UNPAID_LEAVE', 'BEREAVEMENT', 'STUDY_LEAVE', 'COMPASSIONATE', name='absencetype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='absencestatus'), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_absences_employee_id'), 'absences', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_absences_employee_id'), table_name='absences')
    op.drop_table('absences')
    op.drop_index(op.f('ix_absence_balances_year'), table_name='absence_balances')
    op.drop_index(op.f('ix_absence_balances_employee_id'), table_name='absence_balances')
    op.drop_table('absence_balances')
    # ### end Alembic commands ###
