"""add_reporting_tables

Revision ID: 1f53aa31f645
Revises: 3e10dd137943
Create Date: 2025-11-30 18:40:51.215091

"""
from alembic import op
import sqlalchemy as sa


revision = '1f53aa31f645'
down_revision = '3e10dd137943'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.Enum('payroll_summary', 'employee_compensation', 'absence_summary', 'timesheet_summary', 'tax_report', 'custom', name='reporttype', native_enum=False, length=50), nullable=False),
    sa.Column('format', sa.Enum('pdf', 'csv', 'xlsx', 'json', name='reportformat', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='reportstatus', native_enum=False, length=20), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_report_type'), 'reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_type'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
