"""Update timesheet indexes for start_date and end_date

Revision ID: 2e43ee0e93ca
Revises: 04a76a1e49b4
Create Date: 2025-12-15 18:45:20.659948

"""
from alembic import op
import sqlalchemy as sa


revision = '2e43ee0e93ca'
down_revision = '04a76a1e49b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timesheets_work_date'), table_name='timesheets')
    op.create_index(op.f('ix_timesheets_end_date'), 'timesheets', ['end_date'], unique=False)
    op.create_index(op.f('ix_timesheets_start_date'), 'timesheets', ['start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timesheets_start_date'), table_name='timesheets')
    op.drop_index(op.f('ix_timesheets_end_date'), table_name='timesheets')
    op.create_index(op.f('ix_timesheets_work_date'), 'timesheets', ['start_date'], unique=False)
    # ### end Alembic commands ###
