"""add_contract_table

Revision ID: 6ca06ffcd959
Revises: eaee3398eb2a
Create Date: 2025-11-27 13:15:20.019426

"""
from alembic import op
import sqlalchemy as sa


revision = '6ca06ffcd959'
down_revision = 'eaee3398eb2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('contract_type', sa.Enum('FIXED_MONTHLY', 'HOURLY', 'B2B_DAILY', 'B2B_HOURLY', 'TASK_BASED', 'COMMISSION_BASED', name='contracttype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'CANCELED', 'PENDING', name='contractstatus'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('rate_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rate_currency', sa.String(length=3), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('hours_per_week', sa.Integer(), nullable=True),
    sa.Column('commission_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('canceled_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_employee_id'), 'contracts', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contracts_employee_id'), table_name='contracts')
    op.drop_table('contracts')
    # ### end Alembic commands ###
