"""add_payroll_tables

Revision ID: adb5581af7ae
Revises: 126b2645ac16
Create Date: 2025-11-28 18:29:53.409616

"""
from alembic import op
import sqlalchemy as sa


revision = 'adb5581af7ae'
down_revision = '126b2645ac16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payrolls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('period_type', sa.Enum('WEEKLY', 'BIWEEKLY', 'MONTHLY', name='payrollperiodtype'), nullable=False),
    sa.Column('period_start_date', sa.Date(), nullable=False),
    sa.Column('period_end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'PROCESSED', 'PAID', 'CANCELLED', name='payrollstatus'), nullable=False),
    sa.Column('gross_pay', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_taxes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_pay', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payrolls_employee_id'), 'payrolls', ['employee_id'], unique=False)
    op.create_table('payroll_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payroll_id', sa.UUID(), nullable=False),
    sa.Column('line_type', sa.Enum('BASE_SALARY', 'HOURLY_WAGE', 'OVERTIME', 'BONUS', 'COMMISSION', 'DEDUCTION', 'TAX', 'ABSENCE_DEDUCTION', name='payrolllinetype'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['payroll_id'], ['payrolls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payroll_lines')
    op.drop_index(op.f('ix_payrolls_employee_id'), table_name='payrolls')
    op.drop_table('payrolls')
    # ### end Alembic commands ###
