"""add_refresh_token_to_users

Revision ID: b1959073189e
Revises: 8dc1119e3b2e
Create Date: 2025-12-02 12:14:40.323460

"""
from alembic import op
import sqlalchemy as sa


revision = 'b1959073189e'
down_revision = '8dc1119e3b2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token_expires_at')
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###
