"""create_audit_logs_table

Revision ID: bdaa888a8dc8
Revises: 1df343b105cb
Create Date: 2025-12-01 12:19:53.598726

"""
from alembic import op
import sqlalchemy as sa


revision = 'bdaa888a8dc8'
down_revision = '1df343b105cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('EMPLOYEE', 'CONTRACT', 'PAYROLL', 'ABSENCE', 'ABSENCE_BALANCE', 'RATE', 'BONUS', 'DEDUCTION', 'OVERTIME', 'SICK_LEAVE', 'REPORT', 'TIMESHEET', name='entitytype'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('CREATED', 'UPDATED', 'DELETED', 'STATUS_CHANGED', 'APPROVED', 'REJECTED', 'CANCELED', 'ACTIVATED', 'EXPIRED', 'CALCULATED', 'PROCESSED', 'PAID', 'COMPLETED', 'FAILED', name='auditaction'), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_employee_occurred', 'audit_logs', ['employee_id', 'occurred_at'], unique=False)
    op.create_index('idx_audit_entity_type_id', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_occurred_at', 'audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_employee_id'), 'audit_logs', ['employee_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_employee_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_occurred_at', table_name='audit_logs')
    op.drop_index('idx_audit_entity_type_id', table_name='audit_logs')
    op.drop_index('idx_audit_employee_occurred', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
