"""add_index_on_refresh_token

Revision ID: dcd83e9fb888
Revises: b1959073189e
Create Date: 2025-12-02 12:22:59.768155

"""
from alembic import op
import sqlalchemy as sa


revision = 'dcd83e9fb888'
down_revision = 'b1959073189e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_refresh_token', 'users', ['refresh_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_refresh_token', table_name='users')
    # ### end Alembic commands ###
