"""add_compensation_tables

Revision ID: ffd5019eb51e
Revises: 6ca06ffcd959
Create Date: 2025-11-27 13:51:01.461930

"""
from alembic import op
import sqlalchemy as sa


revision = 'ffd5019eb51e'
down_revision = '6ca06ffcd959'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('bonus_type', sa.Enum('PERFORMANCE', 'ANNUAL', 'SIGNING', 'RETENTION', 'PROJECT', name='bonustype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bonuses_employee_id'), 'bonuses', ['employee_id'], unique=False)
    op.create_table('deductions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('deduction_type', sa.Enum('TAX', 'INSURANCE', 'PENSION', 'LOAN', 'OTHER', name='deductiontype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deductions_employee_id'), 'deductions', ['employee_id'], unique=False)
    op.create_table('overtime_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('multiplier', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('threshold_hours', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overtime_rules_employee_id'), 'overtime_rules', ['employee_id'], unique=False)
    op.create_table('rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('rate_type', sa.Enum('BASE_SALARY', 'HOURLY_RATE', 'DAILY_RATE', name='ratetype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rates_employee_id'), 'rates', ['employee_id'], unique=False)
    op.create_table('sick_leave_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_days', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sick_leave_rules_employee_id'), 'sick_leave_rules', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sick_leave_rules_employee_id'), table_name='sick_leave_rules')
    op.drop_table('sick_leave_rules')
    op.drop_index(op.f('ix_rates_employee_id'), table_name='rates')
    op.drop_table('rates')
    op.drop_index(op.f('ix_overtime_rules_employee_id'), table_name='overtime_rules')
    op.drop_table('overtime_rules')
    op.drop_index(op.f('ix_deductions_employee_id'), table_name='deductions')
    op.drop_table('deductions')
    op.drop_index(op.f('ix_bonuses_employee_id'), table_name='bonuses')
    op.drop_table('bonuses')
    # ### end Alembic commands ###
